# Generated by Django 5.1.4 on 2025-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("women", "0003_alter_women_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="women",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Черновик"), (1, "Опубликован")], default=0
            ),
        ),
    ]
